In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# URL halaman yang ingin di-scrape
url = 'https://www.marinevesseltraffic.com/ship-owner-manager-ism-data/SEA-ROSE/9481647/525501836'

# Mengirim permintaan GET ke URL
response = requests.get(url)

# Memeriksa apakah permintaan berhasil
if response.status_code == 200:
    # Parsing konten halaman dengan BeautifulSoup
    soup = BeautifulSoup(response.content, 'html.parser')

    # Mencari tabel berdasarkan kelas yang diberikan
    table = soup.find('table', class_='ship-owner-manager-ism-info__table')

    # Membaca tabel dengan pandas
    df = pd.read_html(str(table))[0]

    # Melakukan transpose DataFrame
    df_transposed = df.set_index('VESSEL INFORMATION').transpose()

    # Menyimpan data ke file Excel
    df_transposed.to_excel('ship_data_transposed.xlsx', index=False)

    print('Data berhasil di-scrape dan disimpan dalam file ship_data_transposed.xlsx')
else:
    print(f'Permintaan gagal dengan status kode: {response.status_code}')

Data berhasil di-scrape dan disimpan dalam file ship_data_transposed.xlsx

In [ ]:
df_1 = pd.read_excel('ship_data_transposed.xlsx')

In [ ]:
df_1

,Name,Former names (up to year),"Ship type, detailed","Ship type, AIS",Service Status,Flag,Home Port,IMO,MMSI,Call Sign,Built,Age,Builder,Gross Tonnage,Summer DWT,Length,Beam
0,SEA ROSE,Chang Xing 2032 (2011),Bulk Carrier,Cargo,"Active, Commissioned",Indonesia,NaN,9481647,525501836,YDCD3,2011,13 years,NaN,62272,106668,253 m / 830 ft,43 m / 141 ft

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Fungsi untuk scraping detail kapal
def scrape_ship_details(ship_url):
    response = requests.get(ship_url)
    if response.status_code == 200:
        soup = BeautifulSoup(response.content, 'html.parser')
        table = soup.find('table', class_='ship-owner-manager-ism-info__table')
        if table:
            df = pd.read_html(str(table))[0]
            df_transposed = df.set_index('VESSEL INFORMATION').transpose()
            return df_transposed
    return pd.DataFrame()

# Fungsi untuk mendapatkan URL kapal dari halaman daftar kapal
def get_ship_urls(page_url):
    response = requests.get(page_url)
    if response.status_code == 200:
        soup = BeautifulSoup(response.content, 'html.parser')
        ship_links = soup.find_all('a', class_='ship-details-link')
        base_url = 'https://www.marinevesseltraffic.com'
        ship_urls = [base_url + link.get('href') for link in ship_links]
        return ship_urls
    return []

# URL halaman daftar kapal
base_page_url = 'https://www.marinevesseltraffic.com/vessels?page={}&flag=ID'

# Menyimpan semua detail kapal dalam satu DataFrame
all_ship_details = pd.DataFrame()

# Loop melalui beberapa halaman (misalnya, 3 halaman pertama)
for page_num in range(1, 4):  # Anda bisa menyesuaikan jumlah halaman sesuai kebutuhan
    page_url = base_page_url.format(page_num)
    ship_urls = get_ship_urls(page_url)

    for ship_url in ship_urls:
        ship_details = scrape_ship_details(ship_url)
        all_ship_details = pd.concat([all_ship_details, ship_details], ignore_index=True)

# Menyimpan semua detail kapal ke file Excel
all_ship_details.to_excel('all_ship_details.xlsx', index=False)

print('Data berhasil di-scrape dan disimpan dalam file all_ship_details.xlsx')

Data berhasil di-scrape dan disimpan dalam file all_ship_details.xlsx

In [ ]:
df_2 = pd.read_excel('all_ship_details.xlsx')

In [ ]:
df_2

Empty DataFrame
Columns: []
Index: []